---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-credentials
  namespace: default
spec:
  encryptedData:
    connection: AgAFL4X2DBbjP1vsSpj6HanOGm5oyXef2Qfw4LDPt0JHn820nSBJQHfxyYLAlMYiKUnWve9fhgDzHCwtYi45YUwaOPra3PTyOJ7M/53OpsDB9HXxnXrhUY9T6hjF/1z1NbOlLAUY+z/eRHmZiSnJ4JuHUQQnPLN051SR+BIHXAnByES6BBk6oC9ZDpITpnAiH37nYatnOMIJWWku9ftrNqunPBsAbi67Nrs99uxU8QhkPPiX/fQfFoSYiiMOm16EXSTGZQy+/MzWxNdSWXzFbe1Z0e8bxEbXVV2+781wbanPlwcbvxLpUh9CUs3m5KMLlsHOZ7jolj9XXO7g6vB2kiI1TWiwpEsfuP8LAkiU9dMaZ8qlVA8tIP79SPMDfq4EQWKa5Fw0aDavV7kfmP+CRcxuOxS8NjgvjhPm+d7Yw+KhsXNvCpTeEqefkFo7IWjXrlAAiUx3M7L6h44T2i8OIZx4/wv7aAtltLg9MizXqPqucVRMSL6gYl7KMHXgqwCcEaYpZ/6j36SHLRua44O5Cw3RJasPF8MQmoWaDPkjyluM9Nq5iZ9YLqGwJyw3IxfMfp0nORzYvB9UiMGIPWWwRhvi+EAi+mB+GijX7YgfY+Jtt5UbI6jQiNs26XKa/qCYdeJLlXt+1WdaeNlcLak4UEQ+4vB6ewBhxUWv6mAH/EvA+P59eqTg8lPvSe5YN9ah1PHClZUZ4wpJj1jFww/9xh9OLS8NjNXsWWfL8KbmoEHKQ08=
    password: AgBYeh7MVazl3YxxQk60Jk6WB9I5XQP54ln8CZ+zpzhWemnbKnEazKrc/jJe0QAxDzbh8T1yr1vqhoOoDwsuc6h20crK7XQGpQCCI4/8S+5paHgf4kU5RXL/npH9mgdU8KnuScVWvJh8qNPq6WcAjwVZZGA6ex6G+Mj/EOcaT09XQ+BJ3vHo6QbI8bv23czhoQ/CYoS2E134ULIFM8Vt8L/2QyIS3R1VpXQg0cqHWrWDbZmkJnQESFyadVmLSxyp9o44egwhxB+FXFQq6rynnlzSIDm68rFP0f7Fd1U1qKXyZssRYmjQpgCdwFOV8sQ1uJm6Vha2Wv4qxxL/j1uHcvo8pCtZwMzeaniJ80+JsEcblBVYR7nLjnh/VnszoSiF4I37TsLnmMiu3EV8ujK7lQ+T85LNzQoLWkGRS3WqNiCI9umx+VhLbKjECcFf2rVq53OWgGWauHK82Nd9z73zg5cQQ9Os2FJa4vRT7SfAlde5OBDnP35kYT1HoRuoUsGyH2hSaKngkbq+pTzGaIXfxI3WAIfUcEkIqLjnyEWhYukzHRp0N1FqM5W/9+7WoBpD6dBNcVJZY0l6sxt605+xeBrrFRVICufWOBE8wYERM00U9FExWaldNH133+OyWr1NCz2xirdBpStTLg9vKOghluK2gf3HjX5dhssykpnkp7hpSoG2nGeC8ZykArrGrilOgBkrTKgWI4RMYJTmsJfHfco=
    username: AgBDaHNhHtF/93kY8YSwLM/bYiLpbyJLoKn4NAQjzwXQFo3soJIPhSmhinrKBmSGcrZb1CwFpqS6P3BZOEaJFo7JnAGQUJdTJ3Vvk+RAlnehjBuCO+vklfDkSOQA+t2hWxGpVtoii2u/xcKbk7I6fkTP90rfjvM1c43oEGlShsnfMzb9uM2NZTdjWdDthxKIcSQfXuJJtSCrudOe02HTE45yqkQeQrYh+MLt7XkIErcLShveFFGhN+ZNbVOhIjwku6sTDpXWwYAfD0IkHnmrm3VDa+NPnssLeLvAYgeJ9Nprujfqsev5zDpZtcwxTCgN8UNPBUqhhSTY6lpenw0H4jIhrsTvxClNclO9edH2ckRlvFNmuaTfxkO2ekc/RduwB6bpxGyU1OzSqMq1+YdcnbN99XI281bf9R0oe7jntkgpzDueqG72yGjCBEee1p54mXrW8vLl4bfE27Vr3FGmJgR1QulLHrrjNAdbMk7reR1exs6zWTAKllqhT6/kjjv2OyuvBftjDa79/qqXzzzq+PgKHmHFWTBFQhtMO7wZ5oIee3by2vnnn9PuxRrPNjvHunLNSzNd9rCPPjAHTM726rU41psSUdMbPdyykKu6HaDJzjd+Xa+x+ZjQjwEFseJpoNzBvS1nFoRpz41chttAvBmtS5bVh6WiCEVPLaNY/b5/lsCUTMfxxtQiUxQcAGotKv9H/eThZSphGrqfuw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysql-credentials
      namespace: default
    type: Opaque

